#ifndef _RX_FOLD_INCLUDED
#define _RX_FOLD_INCLUDED

#define _rx_fold(f, initial, n, ...) \
	rx_paste(_rx_fold_, n)(f, initial, __VA_ARGS__)

// ruby -e '2.upto(64).each {|n| puts "#define _rx_fold_#{n}(f, initial, each, ...)\t\tf(_rx_fold_#{n-1}(f, each, __VA_ARGS__), initial)"}'

#define _rx_fold_1(f, initial, each)			f(each, initial)
#define _rx_fold_2(f, initial, each, ...)		f(_rx_fold_1(f, each, __VA_ARGS__), initial)
#define _rx_fold_3(f, initial, each, ...)		f(_rx_fold_2(f, each, __VA_ARGS__), initial)
#define _rx_fold_4(f, initial, each, ...)		f(_rx_fold_3(f, each, __VA_ARGS__), initial)
#define _rx_fold_5(f, initial, each, ...)		f(_rx_fold_4(f, each, __VA_ARGS__), initial)
#define _rx_fold_6(f, initial, each, ...)		f(_rx_fold_5(f, each, __VA_ARGS__), initial)
#define _rx_fold_7(f, initial, each, ...)		f(_rx_fold_6(f, each, __VA_ARGS__), initial)
#define _rx_fold_8(f, initial, each, ...)		f(_rx_fold_7(f, each, __VA_ARGS__), initial)
#define _rx_fold_9(f, initial, each, ...)		f(_rx_fold_8(f, each, __VA_ARGS__), initial)
#define _rx_fold_10(f, initial, each, ...)		f(_rx_fold_9(f, each, __VA_ARGS__), initial)
#define _rx_fold_11(f, initial, each, ...)		f(_rx_fold_10(f, each, __VA_ARGS__), initial)
#define _rx_fold_12(f, initial, each, ...)		f(_rx_fold_11(f, each, __VA_ARGS__), initial)
#define _rx_fold_13(f, initial, each, ...)		f(_rx_fold_12(f, each, __VA_ARGS__), initial)
#define _rx_fold_14(f, initial, each, ...)		f(_rx_fold_13(f, each, __VA_ARGS__), initial)
#define _rx_fold_15(f, initial, each, ...)		f(_rx_fold_14(f, each, __VA_ARGS__), initial)
#define _rx_fold_16(f, initial, each, ...)		f(_rx_fold_15(f, each, __VA_ARGS__), initial)
#define _rx_fold_17(f, initial, each, ...)		f(_rx_fold_16(f, each, __VA_ARGS__), initial)
#define _rx_fold_18(f, initial, each, ...)		f(_rx_fold_17(f, each, __VA_ARGS__), initial)
#define _rx_fold_19(f, initial, each, ...)		f(_rx_fold_18(f, each, __VA_ARGS__), initial)
#define _rx_fold_20(f, initial, each, ...)		f(_rx_fold_19(f, each, __VA_ARGS__), initial)
#define _rx_fold_21(f, initial, each, ...)		f(_rx_fold_20(f, each, __VA_ARGS__), initial)
#define _rx_fold_22(f, initial, each, ...)		f(_rx_fold_21(f, each, __VA_ARGS__), initial)
#define _rx_fold_23(f, initial, each, ...)		f(_rx_fold_22(f, each, __VA_ARGS__), initial)
#define _rx_fold_24(f, initial, each, ...)		f(_rx_fold_23(f, each, __VA_ARGS__), initial)
#define _rx_fold_25(f, initial, each, ...)		f(_rx_fold_24(f, each, __VA_ARGS__), initial)
#define _rx_fold_26(f, initial, each, ...)		f(_rx_fold_25(f, each, __VA_ARGS__), initial)
#define _rx_fold_27(f, initial, each, ...)		f(_rx_fold_26(f, each, __VA_ARGS__), initial)
#define _rx_fold_28(f, initial, each, ...)		f(_rx_fold_27(f, each, __VA_ARGS__), initial)
#define _rx_fold_29(f, initial, each, ...)		f(_rx_fold_28(f, each, __VA_ARGS__), initial)
#define _rx_fold_30(f, initial, each, ...)		f(_rx_fold_29(f, each, __VA_ARGS__), initial)
#define _rx_fold_31(f, initial, each, ...)		f(_rx_fold_30(f, each, __VA_ARGS__), initial)
#define _rx_fold_32(f, initial, each, ...)		f(_rx_fold_31(f, each, __VA_ARGS__), initial)
#define _rx_fold_33(f, initial, each, ...)		f(_rx_fold_32(f, each, __VA_ARGS__), initial)
#define _rx_fold_34(f, initial, each, ...)		f(_rx_fold_33(f, each, __VA_ARGS__), initial)
#define _rx_fold_35(f, initial, each, ...)		f(_rx_fold_34(f, each, __VA_ARGS__), initial)
#define _rx_fold_36(f, initial, each, ...)		f(_rx_fold_35(f, each, __VA_ARGS__), initial)
#define _rx_fold_37(f, initial, each, ...)		f(_rx_fold_36(f, each, __VA_ARGS__), initial)
#define _rx_fold_38(f, initial, each, ...)		f(_rx_fold_37(f, each, __VA_ARGS__), initial)
#define _rx_fold_39(f, initial, each, ...)		f(_rx_fold_38(f, each, __VA_ARGS__), initial)
#define _rx_fold_40(f, initial, each, ...)		f(_rx_fold_39(f, each, __VA_ARGS__), initial)
#define _rx_fold_41(f, initial, each, ...)		f(_rx_fold_40(f, each, __VA_ARGS__), initial)
#define _rx_fold_42(f, initial, each, ...)		f(_rx_fold_41(f, each, __VA_ARGS__), initial)
#define _rx_fold_43(f, initial, each, ...)		f(_rx_fold_42(f, each, __VA_ARGS__), initial)
#define _rx_fold_44(f, initial, each, ...)		f(_rx_fold_43(f, each, __VA_ARGS__), initial)
#define _rx_fold_45(f, initial, each, ...)		f(_rx_fold_44(f, each, __VA_ARGS__), initial)
#define _rx_fold_46(f, initial, each, ...)		f(_rx_fold_45(f, each, __VA_ARGS__), initial)
#define _rx_fold_47(f, initial, each, ...)		f(_rx_fold_46(f, each, __VA_ARGS__), initial)
#define _rx_fold_48(f, initial, each, ...)		f(_rx_fold_47(f, each, __VA_ARGS__), initial)
#define _rx_fold_49(f, initial, each, ...)		f(_rx_fold_48(f, each, __VA_ARGS__), initial)
#define _rx_fold_50(f, initial, each, ...)		f(_rx_fold_49(f, each, __VA_ARGS__), initial)
#define _rx_fold_51(f, initial, each, ...)		f(_rx_fold_50(f, each, __VA_ARGS__), initial)
#define _rx_fold_52(f, initial, each, ...)		f(_rx_fold_51(f, each, __VA_ARGS__), initial)
#define _rx_fold_53(f, initial, each, ...)		f(_rx_fold_52(f, each, __VA_ARGS__), initial)
#define _rx_fold_54(f, initial, each, ...)		f(_rx_fold_53(f, each, __VA_ARGS__), initial)
#define _rx_fold_55(f, initial, each, ...)		f(_rx_fold_54(f, each, __VA_ARGS__), initial)
#define _rx_fold_56(f, initial, each, ...)		f(_rx_fold_55(f, each, __VA_ARGS__), initial)
#define _rx_fold_57(f, initial, each, ...)		f(_rx_fold_56(f, each, __VA_ARGS__), initial)
#define _rx_fold_58(f, initial, each, ...)		f(_rx_fold_57(f, each, __VA_ARGS__), initial)
#define _rx_fold_59(f, initial, each, ...)		f(_rx_fold_58(f, each, __VA_ARGS__), initial)
#define _rx_fold_60(f, initial, each, ...)		f(_rx_fold_59(f, each, __VA_ARGS__), initial)
#define _rx_fold_61(f, initial, each, ...)		f(_rx_fold_60(f, each, __VA_ARGS__), initial)
#define _rx_fold_62(f, initial, each, ...)		f(_rx_fold_61(f, each, __VA_ARGS__), initial)
#define _rx_fold_63(f, initial, each, ...)		f(_rx_fold_62(f, each, __VA_ARGS__), initial)
#define _rx_fold_64(f, initial, each, ...)		f(_rx_fold_63(f, each, __VA_ARGS__), initial)

#endif
